### ISSUE TITLE
acpi.h : Necessary header file not included

### ISSUE THREAD

**Issue by healytpk** [RobertCNelson/barebox#1]
"acpi.h" can cause a build failure because it doesn't include the necessary header file for "memcmp".

I'm not sure if this is by design (i.e. I'm not sure if you are supposed to include "common.h" before all other headers).

**Comment by RobertCNelson** [comment]
@healytpk thanks for your feedback, but i'm not the maintainer of this project.. Closing and locking the repo..

Regards,
